export const config = {
  IS_MOBILE: 800,
  IS_TIMEOUT: 800,

  IS_MIN_WIDTH: 450,

  NUMBER_DESKTOP: 16,
  NUMBER_MIDDLE: 8,
  NUMBER_MOBILE: 5,

  INCREMENT_DESKTOP: 4,
  INCREMENT_MIDDLE: 2,
  INCREMENT_MOBILE: 2,
}